name: Ovládání WiFi relé (9-18)

on:
  schedule:
    - cron: '0 9-18 * * *'  # každou hodinu od 09:00 do 18:00 UTC -> upravte pro vaše timezone
  workflow_dispatch:

jobs:
  ovladani:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OTE prices artifact
        uses: actions/download-artifact@v4
        with:
          name: ote-ceny
          path: .

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install pandas requests tuyapy2

      - name: Run ovladani_rele.py
        env:
          LIMIT_EUR: ${{ secrets.LIMIT_EUR }}             # volitelné
          TUYA_ACCESS_ID: ${{ secrets.TUYA_ACCESS_ID }}
          TUYA_ACCESS_SECRET: ${{ secrets.TUYA_ACCESS_SECRET }}
          TUYA_EMAIL: ${{ secrets.TUYA_EMAIL }}
          TUYA_PASSWORD: ${{ secrets.TUYA_PASSWORD }}
          DEVICE_NAME: ${{ secrets.DEVICE_NAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          POKUSY: '3'
          CEKANI: '60'
        run: python ovladani_rele.py
