name: ovladani_rele

on:
  schedule:
    - cron: "48 5-17 * 11,12,1,2 *"
    - cron: "48 1-18 * 4,5,6,7,8,9 *"
  workflow_dispatch:

concurrency:
  group: ovladani-wifi-rele
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      MQTT_BROKER: ${{ secrets.MQTT_BROKER }}
      MQTT_PORT: ${{ secrets.MQTT_PORT }}
      MQTT_USER: ${{ secrets.MQTT_USER }}
      MQTT_PASS: ${{ secrets.MQTT_PASS }}
      MQTT_BASE: ${{ secrets.MQTT_BASE }}

      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      GH_TOKEN_CUSTOM: ${{ secrets.MY_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas requests paho-mqtt

      - name: Run script
        run: python ovladani_rele.py
